development:
  adapter: postgresql
  encoding: unicode
  database: bike_parking_san_fran_development
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: bike_parking_san_fran_test
  host: localhost 

production:
  adapter: postgresql
  host: localhost
  database: bike_parking_san_fran_production

