development:
  adapter: postgresql
  encoding: unicode
  database: bike_parking_san_fran_development
  host: localhost
  username: bobbilee
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: bike_parking_san_fran_test
  host: localhost
  username: bobbilee
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: bike_parking_san_fran_production
  host: localhost

